# This actions is for building a Development Environment Image
# For details: README> CI Pipeline Strategy

name: "dev_build_image"
description: "Steps for building a Development Environment Image"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Define a build cache
      uses: actions/cache@v3
      # Setting up the cache so that it can be used for docker build
      with:
        path: /tmp/.build_cache
        # The build cache key is essential for effective and efficient caching.
        # Track files which upon change should yield to producing a new
        # Development Environment image.
        key: >-
          ${{ runner.os }}_build_cache_${{ hashFiles(
            'mise.toml',
            'pyproject.toml',
            'poetry.lock',
            'build/Dockerfile',
            '.dockerignore'
          ) }}

        restore-keys: |
          ${{ runner.os }}_build_cache_

    - name: Build dev image
      shell: bash
      # By using --cache-from and --cache-to docker build can use results from previous builds
      # done even by other runs of workflows. --load \
      run: |
        docker buildx build \
        --cache-from=type=local,src=/tmp/.build_cache \
        --cache-to=type=local,dest=/tmp/.build_cache,mode=max \
        -f build/Dockerfile \
        --target dev \
        --load \
        -t koda:dev .

    - name: Build prod image
      shell: bash
      # By using --cache-from and --cache-to docker build can use results from previous builds
      # done even by other runs of workflows.
      run: |
        docker buildx build \
        --cache-from=type=local,src=/tmp/.build_cache \
        --cache-to=type=local,dest=/tmp/.build_cache,mode=max \
        -f build/Dockerfile \
        --target prod \
        --load \
        -t koda:prod .

    - name: Verify local images
      shell: bash
      run: |
        docker images | grep koda
