version: '3.8'
services:
  terraform:
    build:
      context: .
      dockerfile: terraform2.Dockerfile
    
    #environment:


    #image: hashicorp/terraform:latest
    #volumes:
    #  - .:/app
    volumes:
      - ./:/workspace
    #working_dir: /app
    #command: terraform init

# Instructions to run the Terraform container
#docker-compose build

# Initialize terraform

#docker-compose run --rm terraform init

#docker-compose run --rm terraform validate

# Plan terraform
#docker-compose run --rm terraform plan

# Apply terraform
#docker-compose run --rm terraform apply

# Destroy terraform
#docker-compose run --rm terraform destroy