# This file defines our CI workflow (pipeline)
# For more information: README> CI Pipeline Strategy

name: Continuos Integration Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:

  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Development Environment Image
        uses: ./.github/actions/build_dev_image

      - name: Code analysis checks
        run: docker run --rm koda:dev mise check_code

  code_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Development Environment Image
        uses: ./.github/actions/build_dev_image

      - name: Poetry lock sync-state
        run: docker run --rm koda:dev poetry check

      - name: Run tests in container
        run: docker run --rm koda:dev pytest
